name: Testing
on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - master
    - feature/*
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh